### ISSUE TITLE
laravel 10

### ISSUE THREAD

**Issue by arturasfrontit** [oooholdings/nova-password-generator#28] opened 2023-05-04 07:32 UTC
```bash
dockeruser@e2fe84719edc:~$ composer require outofoffice/password-generator
./composer.json has been updated
Running composer update outofoffice/password-generator
Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - gldrenthe89/nova-string-generator-field[v3.0, ..., v3.0.2] require illuminate/support ^9.0 -> found illuminate/support[v9.0.0, ..., v9.52.7] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires gldrenthe89/nova-string-generator-field 3.* -> satisfiable by gldrenthe89/nova-string-generator-field[v3.0, v3.0.1, v3.0.2].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require outofoffice/password-generator:*" to figure out if any version is installable, or "composer require outofoffice/password-generator:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
dockeruser@e2fe84719edc:~$ 
```

**Comment by btrsco** [comment] 2023-05-07 17:37
I’ll look into this later tonight and ensure it works well with Laravel 10. Thanks for reporting this.

**Comment by btrsco** [comment] 2023-05-08 00:46
I have tried installing `outofoffice/password-generator` on a fresh Laravel 10.8 install. I was not able to replicate this issue. The only dependency that my package has is a PHP dependency and after looking at your issue closer it seems like the issue is being caused by another package you have installed called `gldrenthe89/nova-string-generator-field`.

I have tried installing that (`gldrenthe89/nova-string-generator-field`) package on the fresh Laravel 10.8 install and got the same error as you did. I'd recommend you remove this package or find another way of bypassing this check. Since the issue isn't caused by `outofoffice/password-generator` I will be closing this issue. Thanks

**Closed as not planned by btrsco** 2023-05-08 00:46 UTC
